name: Ejecutar Saldo_Inventario.py cada hora

on:
  schedule:
    - cron: "0 10-23 * * 1-5"  # Se ejecuta cada hora a los 0 minutos (UTC)
  workflow_dispatch:

jobs:
  run-script:
    runs-on: Ubuntu-22.04
    steps:
      - name: Obtener cÃ³digo
        uses: actions/checkout@v3
      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Crear archivo de clave de servicio
        run: echo "$SERVICE_KEY" > key.json
        env:
          SERVICE_KEY: ${{ secrets.SERVICE_KEY }}
      - name: Ejecutar script
        run: python Saldo_Inventario.py
